version: '3.3'
services:
    DVWA:
        ports:
            - '80:80'
            - '4444:4444'
        image: vulnerables/web-dvwa
    OWASP_Goat:
        ports:
            - '8080:8080'
        environment:
            - TZ=America/Toronto
        image: webgoat/goatandwolf
